config/routes.rb
GadgetApp::Application.routes.draw do

  resources :gadgets, :except => [:show] do
    collection do
      get :search
    end
    resources :gadget_images, :only => [:create, :destroy]
  end
  root :to => "gadgets#index"
  devise_for :users
end

app/models/gadget.rb
class Gadget < ActiveRecord::Base

	belongs_to :user
	has_many :gadget_images, dependent: :destroy

	validates :name, presence: true, uniqueness: {scope: :user_id}
	validates :user_id, presence: true

	def self.search(user, query)
		where("user_id = ? AND name LIKE ?", user.id, "%#{query}%")
	end
end

app/models/gadget_image.rb
class GadgetImage < ActiveRecord::Base

	belongs_to :gadget

	has_attached_file :attachment, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
	
	validates :gadget_id, presence: true
	validates_attachment :attachment, presence: true, content_type: { content_type: /\Aimage\/.*\Z/ }


end

app/models/user.rb
class User < ActiveRecord::Base

	has_many :gadgets

	validates :username, presence: true, uniqueness: true
	validates :password_confirmation, presence: {if: :new_record?}

	devise :database_authenticatable, :registerable, :validatable

	def email_required?
		false
	end

	def email_changed?
		false
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/gadget_images_controller.rb
class GadgetImagesController < ApplicationController

	before_action :authenticate_user!

	def create
		@gadget = current_user.gadgets.find(params[:gadget_id])
		@gadget_image = @gadget.gadget_images.build(params.require(:gadget_image).permit(:attachment))
		@gadget_image.save
		redirect_to edit_gadget_path(@gadget)
	end

	def destroy
		@gadget = current_user.gadgets.find(params[:gadget_id])
		@gadget_image = @gadget.gadget_images.find(params[:id])
		@gadget_image.destroy
		redirect_to edit_gadget_path(@gadget)
	end

end

app/controllers/gadgets_controller.rb
class GadgetsController < ApplicationController

	before_action :authenticate_user!

	def index
		@gadgets = current_user.gadgets
	end

	def new
		@gadget = Gadget.new
	end

	def create
		@gadget = current_user.gadgets.build(name: params[:gadget][:name])
		if @gadget.save
			redirect_to root_path
		else
			render :new
		end
	end

	def search
		@query = params[:q]
		@gadgets = Gadget.search(current_user, @query)
	end

	def edit
		@gadget = current_user.gadgets.find(params[:id])
	end

	def update
		@gadget = current_user.gadgets.find(params[:id])
		if @gadget.update_attributes(name: params[:gadget][:name])
			redirect_to root_path
		else
			render :edit
		end
	end

	def destroy
		@gadget = current_user.gadgets.find(params[:id])
		@gadget.destroy
		redirect_to root_path
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/gadgets/_list.html.erb
<table>
	<thead>
		<tr>
			<th>Name</th>
			<th><%= link_to "Create Gadget", new_gadget_path%></th>
			<th>
				<%= form_tag(search_gadgets_path, method: :get) do %>
					<%= label_tag(:q, "Search for:") %>
					<%= text_field_tag(:q) %>
					<%= submit_tag('Search')%>
				<% end %>
			</th>
		</tr>
	</thead>
	<tbody>
		<%- gadgets.each do |gadget| -%>
			<tr>
				<td><%= gadget.name %></td>
				<td><%= link_to "Edit", edit_gadget_path(gadget)%></td>
				<td><%= link_to "Destroy", gadget_path(gadget), method: :delete%></td>
			</tr>
		<%- end -%>
	</tbody> 
</table>

app/views/gadgets/edit.html.erb
<h1>Edit Gadget</h1>

<%= form_for(@gadget) do |f|%>
  <div><%= f.label :name %><br />
  <%= f.text_field :name %> <br />
  <ul>
  <% @gadget.errors.full_messages.each do |msg| %>
  	<li><%= msg %></li>
  <% end %>	
  </ul></div>

  <div><%= f.submit "Update" %></div>
<% end %>

<div>
	<% @gadget.gadget_images.each do |gadget_image| %>
		<div>
			<%= image_tag gadget_image.attachment.url(:medium) %>
			<%= link_to 'Destroy', gadget_gadget_image_path(@gadget, gadget_image), method: :delete %>
		</div>
	<% end %>
	<%= form_for [@gadget, @gadget.gadget_images.new], html: { multipart: true } do |form| %>
		<%= form.file_field :attachment %>
		<%= form.submit "Send file" %>
	<% end %>
</div>

app/views/gadgets/index.html.erb
<h1>Welcome, <%= current_user.username%></h1>

<h2>Gadgets</h2>
<%= render partial: 'list', locals: {gadgets: @gadgets} %>

app/views/gadgets/new.html.erb
<h1>New Gadget</h1>

<%= form_for(@gadget) do |f|%>
  <div><%= f.label :name %><br />
  <%= f.text_field :name %> <br />
  <ul>
  <% @gadget.errors.full_messages.each do |msg| %>
  	<li><%= msg %></li>
  <% end %>	
  </ul></div>

  <div><%= f.submit "Create gadget" %></div>
<% end %>

app/views/gadgets/search.html.erb
<h1>Search</h1>

<h2>Gadgets</h2>
<table>
	<thead>
		<tr>
			<th>Name</th>
			<th><%= link_to "Create Gadget", new_gadget_path%></th>
			<th>
				<%= form_tag(search_gadgets_path, method: :get) do %>
					<%= label_tag(:q, "Search for:") %>
					<%= text_field_tag(:q) %>
					<%= submit_tag('Search')%>
				<% end %>
			</th>
		</tr>
	</thead>
	<tbody>
		<%- @gadgets.each do |gadget| -%>
			<tr>
				<td><%= gadget.name %></td>
			</tr>
		<%- end -%>
	</tbody> 
</table>

app/views/home/index.html.erb
<h1>Welcome, <%= current_user.username%></h1>

<h2>Gadgets</h2>
<table>
	<thead>
		<tr>
			<th>Name</th>
			<th><%= link_to "Create Gadget", new_gadget_path%></th>
			<th>
				<%= form_tag(search_gadgets_path, method: :get) do %>
					<%= label_tag(:q, "Search for:") %>
					<%= text_field_tag(:q) %>
					<%= submit_tag('Search')%>
				<% end %>
			</th>
		</tr>
	</thead>
	<tbody>
		<%- current_user.gadgets.each do |gadget| -%>
			<tr>
				<td><%= gadget.name %></td>
			</tr>
		<%- end -%>
	</tbody> 
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>GadgetApp</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<div>
		<% if user_signed_in?%>
			<%= link_to 'Log out', destroy_user_session_path, method: Rails.env.test? ? :get : :delete %>
		<%else%>
			<%= link_to 'Log in', new_user_session_path %>
			<%= link_to 'Sign up', new_user_registration_path %>
		<%end%>
	</div>
	<div>
		<p class="notice"><%= notice %></p>
	    <p class="alert"><%= alert %></p>

		<%= yield %>
	</div>
</body>
</html>